# Conda environment
name: project_environment

dependencies:
  - python=3.6.2

pip:
  - azureml-sdk==1.0.33
  - tensorflow==1.10
  - tensorflow-gpu==1.10
  - numpy==1.16.3
  - matplotlib==3.0.3
  - opencv==3.4.2
